local options = {
    clipboard = "unnamedplus",
    cmdheight = 1,
    completeopt = { "menuone", "noselect" },
    conceallevel = 2,
    fileencoding = "utf-8",
    encoding = "utf-8",
    hlsearch = false,
    ignorecase = true,
    mouse = "a",
    pumheight = 10,
    showmode = false,
    showtabline = 2,
    smartcase = true,
    smartindent = true,
    autoindent = true,
    splitbelow = true,
    splitright = true,
    swapfile = false,
    termguicolors = true,
    timeoutlen = 300,
    updatetime = 300,
    expandtab = true,
    shiftwidth = 4,
    tabstop = 4,
    softtabstop = 4,
    number = true,
    relativenumber = false,
    wrapmargin = 80,
    scrolloff = 8,
    smarttab = true,
    backspace = { "eol", "start", "indent" },
    belloff = "all",
    list = true,
    listchars = {tab = "»·", trail = "·"},
    signcolumn = "yes",
}

for k, v in pairs(options) do
    vim.opt[k] = v
end
